# Generated by Django 2.2.4 on 2019-10-13 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('production_year', models.SmallIntegerField()),
                ('place', models.CharField(max_length=15)),
                ('kilometer', models.IntegerField()),
                ('engine_capacity', models.CharField(max_length=25)),
                ('cylinders', models.CharField(max_length=5)),
                ('transmission_type', models.BooleanField()),
                ('fuel', models.BooleanField()),
                ('body_shape', models.CharField(max_length=10)),
                ('seats', models.CharField(max_length=3)),
                ('technical_status', models.CharField(max_length=10)),
                ('outer_color', models.CharField(max_length=15)),
                ('inner_color', models.CharField(max_length=15)),
                ('extra_features', models.TextField(blank=True, null=True)),
                ('image0', models.ImageField(upload_to='cars_pics')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='cars_pics')),
                ('price', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loves', models.ManyToManyField(blank=True, related_name='car_loves', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
    ]
